services:
  sec-dash-backend:
    image: jcivitell/sec-dash-backend
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - "jcivitell/sec-dash-backend:${CIRCLE_TAG:-notag}"
    ports:
      - "8000:8000"
